# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
                ('author', models.CharField(default=b'', max_length=200)),
                ('genre', models.CharField(choices=[(b'fiction', b'fiction'), (b'fear', b'fear'), (b'fear1', b'fear1'), (b'fear2', b'fear2'), (b'fear3', b'fear3')], default=b'fiction', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=b'documents/')),
                ('image', models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[(b'fiction', b'fiction'), (b'fear', b'fear'), (b'fear1', b'fear1'), (b'fear2', b'fear2'), (b'fear3', b'fear3')], default=b'fiction', max_length=30)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Document')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
