# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[(b'fi', b'fiction'), (b'fe', b'fear')], default=b'fi', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='uploader',
            field=models.ForeignKey(default=b'sa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
