# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
