# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20171002_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='text',
        ),
        migrations.AddField(
            model_name='interest',
            name='genre',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
