# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171001_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
