# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171002_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
