# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171002_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'images/'),
        ),
    ]
