# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_document_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploader',
            new_name='user',
        ),
    ]
