# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171003_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.CharField(choices=[(b'fiction', b'fiction'), (b'fear', b'fear'), (b'fear1', b'fear1'), (b'fear2', b'fear2'), (b'fear3', b'fear3')], default=b'fiction', max_length=2),
        ),
    ]
