# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171004_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
