# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171004_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'fiction', b'fiction'), (b'fear', b'fear'), (b'fear1', b'fear1'), (b'fear2', b'fear2'), (b'fear3', b'fear3')], default=b'fiction', max_length=30),
        ),
    ]
