# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_interest_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='genre',
        ),
    ]
